### ISSUE TITLE
parse issue unexpected '@' in program 

### ISSUE THREAD

**Issue by dnamna** [mruegenberg/objc-utils#7]
Am getting this error on build in uikit+drawinghelpers.m any idea?

**Comment by mruegenberg** [comment]
Could you offer a little more detail? The full error message and in particular the file and line number would help.

Also, which compiler are you using? Clang/LLVM or GCC?

**Comment by mruegenberg** [comment]
Closing due to lack of respone. Please reopen if necessary.
