### ISSUE TITLE
UIKit subfolder not in cocoapod

### ISSUE THREAD

**Issue by planerde** [mruegenberg/objc-utils#8]
It seems, that the UIKit subfolder is not included in the podspec. So after installing the pod, I have just the NSFoundation and Util.\* classes.

**Comment by mruegenberg** [comment]
Thanks for catching this!

**Comment by mruegenberg** [comment]
All UIKit-specific functionality has now been extracted to [uikit-utils](https://github.com/mruegenberg/uikit-utils) and [ios-versioncheck](https://github.com/mruegenberg/ios-versioncheck).
