### ISSUE TITLE
NSObject+PerformBlock GCD dispatch_get_current_queue Deprecated.

### ISSUE THREAD

**Issue by BenjaminX** [mruegenberg/objc-utils#9]
Hey mrugenberg,

NSObject+PerformBlock
- (void)performBlock:(void(^)(void))block afterDelay:(NSTimeInterval)delay;
  dispatch_get_current_queue() deprecated in iOS 6.0

maybe remove this message.

**Comment by mruegenberg** [comment]
Fixed with 4d25e71.

I deprecated the method, because it is basically a wrapper for a deprecated API. 

Instead, one should use one of the other two `performBlock:` methods, depending on whether main thread or background execution is wanted.
